[[headers]]
  for = "/*.mp4"
  [headers.values]
    Content-Type = "video/mp4"

[[headers]]
  for = "/*.webm"
  [headers.values]
    Content-Type = "video/webm"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 